pipeline:
  name: test 19 aug
  identifier: test_19_aug
  tags: {}
  projectIdentifier: mohit_test_25_aug
  orgIdentifier: AAAsunnyGitExp
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 1000
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
