pipeline:
  name: dfsdfdsdfdfdd
  identifier: dfsdfds
  projectIdentifier: Default_Project_1667996877169
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: testdfssdfdsdds
        identifier: test
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: test
                  identifier: test
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
