pipeline:
  name: Pipe
  identifier: Pipe
  projectIdentifier: ChetanTestProj
  orgIdentifier: ChetanTestOrg
  tags: {}
  stages:
    - stage:
        name: s123
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "c1"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
