pipeline:
  name: test2aug
  identifier: test2aug
  projectIdentifier: test123
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: tes
        identifier: tes
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1123
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
