pipeline:
  name: test
  identifier: test
  projectIdentifier: test_project_2
  orgIdentifier: adi_org
  tags: {}
  stages:
    - stage:
        name: asfd
        identifier: asfd
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: asfd
                  identifier: asfd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information sdaf
                      and approve the pipeline progression sdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
