pipeline:
  name: test non default branch
  identifier: test_non_default_branch
  projectIdentifier: test_mohit_git_sync_to_gitx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 11s
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: random
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
