pipeline:
  name: test
  identifier: test
  projectIdentifier: test_project_1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: dfs
        identifier: dfs
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fds
                  identifier: fds
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression sdf
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
