pipeline:
  name: test 2
  identifier: test_2
  projectIdentifier: test_project_1
  orgIdentifier: adi_org
  tags: {}
  stages:
    - stage:
        name: sdf
        identifier: sdf
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fsd
                  identifier: fsd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
